### PR TITLE
Adds process exit code so that we can use this in CI

### PR DESCRIPTION
**Pull request by Duder-onomy**

### CODE REVIEW

**Comment by tniezurawski** [comment]
Nice @Duder-onomy! Thanks for that!

Could you add a paragraph to `README.md` about running it on CI? Just a simple example of how you've added it to your pipeline?

**Comment by Duder-onomy** [comment]
@tniezurawski I changed my mind about having this lib check if in CI directly in favor of a config variable / cli argument. 

It seemed to make more sense that the person should be able to opt into this behavior directly. The whole 'if we are in ci' business is not the concern of this lib. 

I added that support and updated the readme. 

There is a diff in the `package-lock.json` that I did not intend. Simply running `npm install` creates that diff. I see there is a `yarn.lock` in the directory as well. Might make sense to switch to yarn until `npm install` creates deterministic builds.

**Comment by tniezurawski** [comment]
Great stuff @Duder-onomy! Thanks for the work you've put into this 🙌

**Comment by tniezurawski** [comment]
Released with `1.1.0` version.

**Pull request merged**
